# Generated by Django 5.2.6 on 2026-02-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_alter_categorymodel_id_alter_productmodel_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
