# Generated by Django 5.2.6 on 2026-02-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='cat_id',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
