# Generated by Django 5.2.6 on 2026-02-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_productmodel_cat_id_delete_categorymodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.BigIntegerField()),
                ('Password', models.CharField(max_length=30)),
                ('Role', models.CharField(max_length=10)),
            ],
        ),
    ]
