# Generated by Django 5.2.6 on 2026-02-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='media/seller')),
                ('price', models.FloatField()),
                ('desc', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorymodel')),
            ],
        ),
    ]
