# Generated by Django 5.2.6 on 2026-02-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_orderitemmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderItemModel',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
