# Generated by Django 5.2.6 on 2026-03-06 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customizationfield_product_customizationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_total', models.FloatField()),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('paymode', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productmodel')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registermodel')),
            ],
        ),
    ]
