# Generated by Django 5.2.6 on 2026-03-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
    ]
