# Generated by Django 5.2.6 on 2026-03-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_freequote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freequote',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
