# Generated by Django 5.2.6 on 2026-03-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_freequote_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomizationField',
        ),
        migrations.DeleteModel(
            name='CustomizationRequest',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
