# Generated by Django 5.2.6 on 2026-03-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_delete_customizationfield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('technician_id', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('physical_cust', models.CharField(choices=[('Phone Cover / Case', 'Phone Cover / Case'), ('Screen Protection & Look', 'Screen Protection & Look'), ('Stickers & Skins', 'Stickers & Skins'), ('Accessories Add-ons', 'Accessories Add-ons'), ('None', 'None'), ('Other', 'Other')], max_length=50)),
                ('software_cust', models.CharField(choices=[('Home Screen Design', 'Home Screen Design'), ('Apps for Customization', 'Apps for Customization'), ('None', 'None'), ('Other', 'Other')], max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='customization/')),
                ('physical_other_cust', models.CharField(blank=True, max_length=200, null=True)),
                ('software_other_cust', models.CharField(blank=True, max_length=200, null=True)),
                ('customization_description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('payment_method', models.CharField(default='Cash on Delivery', max_length=50)),
                ('service_charge', models.IntegerField(default=299)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
