# Generated by Django 5.2.6 on 2026-03-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_customizationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationrequest',
            name='product_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
