# Generated by Django 5.2.6 on 2026-03-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_customizationrequest_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationrequest',
            name='type',
            field=models.CharField(default='Customization', max_length=50),
        ),
        migrations.AlterField(
            model_name='customizationrequest',
            name='product_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
