# Generated by Django 5.2.6 on 2026-03-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_customizationrequest_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationrequest',
            name='laptop_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='customization/'),
        ),
        migrations.AddField(
            model_name='customizationrequest',
            name='laptop_physical_cust',
            field=models.CharField(blank=True, choices=[('Laptop Skin / Cover', 'Laptop Skin / Cover'), ('Screen Protection', 'Screen Protection'), ('RGB Lighting', 'RGB Lighting'), ('Accessories Add-ons', 'Accessories Add-ons'), ('None', 'None'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customizationrequest',
            name='laptop_physical_other_cust',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customizationrequest',
            name='laptop_software_cust',
            field=models.CharField(blank=True, choices=[('UI Customization', 'UI Customization'), ('Performance Optimization', 'Performance Optimization'), ('Software Installation', 'Software Installation'), ('None', 'None'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customizationrequest',
            name='laptop_software_other_cust',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customizationrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='freequote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
