# Generated by Django 5.2.6 on 2026-03-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_customizationrequest_laptop_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizationrequest',
            name='physical_cust',
            field=models.CharField(blank=True, choices=[('Phone Cover / Case', 'Phone Cover / Case'), ('Screen Protection & Look', 'Screen Protection & Look'), ('Stickers & Skins', 'Stickers & Skins'), ('Accessories Add-ons', 'Accessories Add-ons'), ('None', 'None'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customizationrequest',
            name='software_cust',
            field=models.CharField(blank=True, choices=[('Home Screen Design', 'Home Screen Design'), ('Apps for Customization', 'Apps for Customization'), ('None', 'None'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
