# Generated by Django 5.2.6 on 2026-03-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_customizationrequest_physical_cust_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizationrequest',
            name='laptop_cover_image',
        ),
        migrations.RemoveField(
            model_name='customizationrequest',
            name='laptop_physical_cust',
        ),
        migrations.RemoveField(
            model_name='customizationrequest',
            name='laptop_physical_other_cust',
        ),
        migrations.RemoveField(
            model_name='customizationrequest',
            name='laptop_software_cust',
        ),
        migrations.RemoveField(
            model_name='customizationrequest',
            name='laptop_software_other_cust',
        ),
    ]
