# Generated by Django 5.2.6 on 2026-03-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_customizationrequest_physical_cust_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
