# Generated by Django 6.0.2 on 2026-04-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
