# Generated by Django 5.2.6 on 2026-04-08 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='productid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.productmodel'),
        ),
    ]
