# Generated by Django 5.2.6 on 2026-04-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_ordermodel_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='productid',
        ),
    ]
