# Generated by Django 5.2.6 on 2026-04-08 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.registermodel'),
        ),
    ]
