# Generated by Django 5.2.6 on 2026-04-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_productmodel_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='img',
            field=models.ImageField(upload_to='seller/'),
        ),
    ]
