# Generated by Django 5.2.6 on 2026-04-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_productmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='img',
            field=models.ImageField(upload_to='media/seller'),
        ),
    ]
