# Generated by Django 5.2.6 on 2026-04-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_productmodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
