# Generated by Django 5.2.6 on 2026-04-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_productmodel_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='Password',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='Phone',
            field=models.BigIntegerField(unique=True),
        ),
    ]
