# Generated by Django 5.2.6 on 2026-04-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_registermodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='Password',
            field=models.CharField(max_length=30),
        ),
    ]
