# Generated by Django 5.2.6 on 2026-04-13 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
