# Generated by Django 5.2.6 on 2026-04-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='Placed', max_length=20),
        ),
    ]
