# Generated by Django 5.2.6 on 2026-04-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='views',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
