# Generated by Django 5.2.6 on 2026-04-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_repairrequest_service_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizationrequest',
            name='service_charge',
            field=models.IntegerField(default=299, max_length=50),
        ),
    ]
