# Generated by Django 5.2.6 on 2026-04-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_customizationrequest_service_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_status',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(max_length=10),
        ),
    ]
