# Generated by Django 5.2.6 on 2026-04-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_cart_order_status_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(max_length=10),
        ),
    ]
