# Generated by Django 5.2.6 on 2026-04-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_sellerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
