# Generated by Django 5.2.6 on 2026-04-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_sellerprofile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
